package com.UdemyDemo.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
		//Please use username user for logging in and password is the autogenerated one by server
		//Involved spring security for this project in order to get authentication
	}

}
